//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFoodApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int FoodID { get; set; }
        public string FoodTitle { get; set; }
        public string FoodContent { get; set; }
        public string FoodType { get; set; }
        public string FoodImage { get; set; }
        public string FoodShortName { get; set; }
    }
}
